---

freefeed_hostname: circle.ckovalev.com
freefeed_media_hostname: circle-media.ckovalev.com
freefeed_env: release
freefeed_s3_endpoint: ams3.digitaloceanspaces.com
freefeed_s3_bucket: circle-ckovalev
freefeed_storage_type: s3
freefeed_base_port: 3000
freefeed_jobs_enabled: true
react_client_enabled: true
react_client_hostname: circle.ckovalev.com
react_client_version: latest
client_blue_port: 8080
client_green_port: 8081

auth_token_prefix: circle

# gateway on freefeed docker network
postgres_host: 172.18.0.1
postgres_port: 5432
postgres_user: freefeed
postgres_dbname: freefeed
postgres_textsearch_config: pg_catalog.russian

new_relic_app_name: "Circle"
public_sentry_dsn: 'https://abdac1f2db2d45efaa9142062fe14bd8@sentry.io/75960'
monitor_prefix: circle
freefeed_external_auth_providers_enabled: true
redis_host: "redis-{{ freefeed_env }}"
freefeed_server_instances: 1
freefeed_frontend_scheme: http

ansible_python_interpreter: /usr/bin/python3
