---

nginx_user: nginx
nginx_group: nginx

react_client_dir: /var/www/freefeed-react-client
react_client_image: "ckovalev/freefeed-react-client:{{ react_client_version }}"
react_client_hostname: "{{ inventory_hostname }}"

local_storage_whoami_cache_key: whoamiCache
recaptcha_client_secret: ""
public_sentry_dsn: 'https://0123456789abcdef0123456789abcdef@app.getsentry.com/12345'
frontend_scheme: http
